### ISSUE TITLE
功能建议，谢谢！

### ISSUE THREAD

**Issue by chineselzh** [xiaofei86/BitcronTheme#1]
大大您好！非常感谢带来这么优秀的模板！
使用过程中有两点建议，希望考虑：
1、不修改文章发布时间的基础上增加文章置顶功能
2、增加文章的密码保护功能，可参考：https://github.com/yamakong/Bitcron-theme-Slimwriter
谢谢大大！

**Comment by xiaofei86** [comment]
谢谢。挺好的建议。我暂时实现了文章置顶的功能。在博客头部加上 “Pin: True” ，当前文章就会在首页置顶显示。“密码保护”的功能等最近有时间再做，完成了到时候再通知你。

**Comment by xiaofei86** [comment]
两个功能都做完了。使用 Hint（提示） 和 Password（密码）两个字段来设定问题与密码。

手机版效果：
<img width="320" alt="Phone" src="https://user-images.githubusercontent.com/8192632/29005141-4c7982c4-7b07-11e7-9db8-94cab6992f18.jpg">
PC效果：
<img width="426" alt="PC" src="https://user-images.githubusercontent.com/8192632/29005143-56777d58-7b07-11e7-8f19-ca478b536e27.png">

**Comment by chineselzh** [comment]
@xiaofei86 非常感谢大侠！
大侠太历害了！
希望这个主题能不断完善更新！
谢谢谢谢！
